name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (Cypress)
        working-directory: ./CYPRESS-AMAZON-TEST
        run: npm install

      - name: Run Cypress tests
        working-directory: ./CYPRESS-AMAZON-TEST
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
          record: true
          parallel: true
          group: "Cypress Tests"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload test results (if needed)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: CYPRESS-AMAZON-TEST/cypress/screenshots

  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies (Python)
        working-directory: ./Test set
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        working-directory: ./Test set
        run: |
          pytest tests/ -v --html=reports/report.html

      - name: Upload test results (if needed)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: api-test-results
          path: Test set/reports/report.html